<?php

/**
 * @file
 * Contains hook implementations for the finders module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\finders\Hook\EntityHooks;

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  return \Drupal::service(EntityHooks::class)->entityBundleFieldInfo($entity_type, $bundle, $base_field_definitions);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_entity_field_storage_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(EntityHooks::class)->entityFieldStorageInfo($entity_type);
}
