<?php

/**
 * @file
 * Contains hook implementations for the localgov_finders module.
 */

use Drupal\Core\Entity\ContentEntityTypeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Render\Element;
use Drupal\localgov_finders\Hook\EntityHooks;
use Drupal\node\NodeTypeInterface;

/**
 * Implements hook_entity_bundle_field_info().
 */
function localgov_finders_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle_id, array $base_field_definitions): array {
  // Only act on content entity types.
  if (!$entity_type instanceof ContentEntityTypeInterface) {
    return [];
  }

  // Only act on entity types whose bundles are provided by a bundle entity
  // type.
  $bundle_type_id = $entity_type->getBundleEntityType();
  if (empty($bundle_type_id)) {
    return [];
  }

  // On a node type creation form, there is no node type yet.
  $bundle = \Drupal::service('entity_type.manager')->getStorage($bundle_type_id)->load($bundle_id);
  if (empty($bundle)) {
    return [];
  }

  // Get finder type, if there is one.
  $finder_type_manager = \Drupal::service('plugin.manager.localgov_finders_finder_type');
  $finder_type = $finder_type_manager->getBundleFinderType($bundle);
  if (empty($finder_type)) {
    return [];
  }

  $finder_config_manager = \Drupal::service('localgov_finders.finder_config_manager');
  return $finder_config_manager->getBundleFieldDefinitions($bundle);
}

/**
 * Implements hook_entity_field_storage_info().
 */
function localgov_finders_entity_field_storage_info(EntityTypeInterface $entity_type) {
  // Only act on content entity types.
  if (!$entity_type instanceof ContentEntityTypeInterface) {
    return [];
  }

  // Only act on entity types whose bundles are provided by a bundle entity
  // type.
  $bundle_entity_type_id = $entity_type->getBundleEntityType();
  if (empty($bundle_entity_type_id)) {
    return [];
  }

  /** @var \Drupal\localgov_finders\Field\BundleFieldDefinition[] $fields */
  $fields = [];

  $entity_type_manager = \Drupal::service('entity_type.manager');
  $bundle_entities = $entity_type_manager->getStorage($bundle_entity_type_id)->loadMultiple();

  /** @var \Drupal\localgov_finders\FinderConfigManager $finder_config_manager */
  $finder_config_manager = \Drupal::service('localgov_finders.finder_config_manager');
  foreach ($bundle_entities as $bundle_entity) {
    $bundle_fields = $finder_config_manager->getBundleFieldDefinitions($bundle_entity);

    // Check that plugins don't change base field properties from other
    // plugins.
    foreach ($bundle_fields as $field_name => $bundle_field) {
      if (isset($fields[$field_name])) {
        assert($bundle_field->getType() == $fields[$field_name]->getType());
        assert($bundle_field->getTargetEntityTypeId() == $fields[$field_name]->getTargetEntityTypeId());
        assert($bundle_field->getCardinality() == $fields[$field_name]->getCardinality());
        // @todo Check field settings could cause problems if changed, such as
        // entity reference target type.
      }
    }

    $fields += $bundle_fields;
  }

  return $fields;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter(): node_type_form.
 */
function localgov_finders_form_node_type_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\node\NodeTypeInterface $node_type */
  $node_type = $form_state->getFormObject()->getEntity();

  $form['localgov_finders'] = [
    '#type' => 'details',
    '#group' => 'additional_settings',
    '#title' => t('LocalGov Finder type'),
    '#attributes' => ['class' => ['localgov-finders-type']],
    '#tree' => TRUE,
    '#weight' => 10,
  ];

  $finder_type_definitions = \Drupal::service('plugin.manager.localgov_finders_finder_type')->getDefinitions();

  // @todo Remove empty options when
  // https://www.drupal.org/project/drupal/issues/3194345 is fixed in core.
  $options = [
    '' => t('None'),
  ];
  $options += array_map(fn($definition) => $definition['label'], $finder_type_definitions);

  $form['localgov_finders']['finder_type'] = [
    '#type' => 'radios',
    '#title' => t("Finder type"),
    '#options' => $options,
    '#empty_value' => '',
    '#default_value' => $node_type->getThirdPartySetting('localgov_finders', 'finder_type', ''),
  ];

  foreach ($finder_type_definitions as $finder_type_id => $definition) {
    $form['localgov_finders']['finder_type'][$finder_type_id]['#description'] = $definition['description'];
  }

  $form['localgov_finders']['finder_role'] = [
    '#type' => 'radios',
    '#title' => t("Finder role"),
    '#options' => [
      '' => t('None'),
      'channel' => t('Finder channel: nodes of this type are finders'),
      'entries' => t('Entries: nodes of this type are entries that can be shown in finders'),
    ],
    '#default_value' => $node_type->getThirdPartySetting('localgov_finders', 'finder_role', ''),
    // @todo Use States to hide this & make it required if a type is selected.
  ];

  // Don't allow removal of finder type fields.
  // @todo Add support for removing finder configuration.
  $form['localgov_finders']['finder_type']['#disabled'] = !empty($form['localgov_finders']['finder_type']['#default_value']);
  $form['localgov_finders']['finder_role']['#disabled'] = !empty($form['localgov_finders']['finder_role']['#default_value']);

  foreach (Element::children($form['actions']) as $action) {
    $form['actions'][$action]['#validate'][] = 'localgov_finders_form_node_type_form_validate';
    $form['actions'][$action]['#submit'][] = 'localgov_finders_form_node_type_form_submit';
  }
}

/**
 * Validation handler.
 *
 * @see localgov_finders_form_node_type_form_alter()
 */
function localgov_finders_form_node_type_form_validate(array $form, FormStateInterface $form_state) {
  if (!empty($form_state->getValue(['localgov_finders', 'finder_type'])) && empty($form_state->getValue(['localgov_finders', 'finder_role']))) {
    $form_state->setError($form['localgov_finders']['finder_role'], t('The Finder role must be set if a Finder type is set.'));
  }
}

/**
 * Submit handler.
 *
 * @see localgov_finders_form_node_type_form_alter()
 */
function localgov_finders_form_node_type_form_submit(array $form, FormStateInterface $form_state) {
  $node_type = $form_state->getFormObject()->getEntity();
  assert($node_type instanceof NodeTypeInterface);

  if (!empty($form_state->getValue(['localgov_finders', 'finder_type'])) && empty($form_state->getValue(['localgov_finders', 'finder_role']))) {
    $node_type->setThirdPartySetting(
      'localgov_finders',
      'finder_type',
      $form_state->getValue(['localgov_finders', 'finder_type'])
    );
    $node_type->setThirdPartySetting(
      'localgov_finders',
      'finder_role',
      $form_state->getValue(['localgov_finders', 'finder_role'])
    );
    $node_type->save();
  }
}

#[LegacyHook]
function localgov_finders_entity_insert(EntityInterface $entity): void {
  \Drupal::service(EntityHooks::class)->entityInsert($entity);
}

#[LegacyHook]
function localgov_finders_entity_update(EntityInterface $entity): void {
  \Drupal::service(EntityHooks::class)->entityUpdate($entity);
}
