finders.finder.*:
  type: config_entity
  label: Finder
  mapping:
    id:
      type: text
      label: Machine name
    label:
      type: label
      label: Name
    type:
      type: text
      label: Finder type
    channels:
      type: sequence
      label: Finder channels
      sequence:
        type: sequence
        label: Finder channel bundles
        sequence:
          type: text
          label: Bundle name
    entries:
      type: sequence
      label: Finder entries
      sequence:
        type: sequence
        label: Finder channel bundles
        sequence:
          type: text
          label: Bundle name
    third_party_settings:
      requiredKey: false
      type: sequence
      label: 'Third party settings'
      sequence:
        type: finders.finder.third_party.[%key]
