finders.finder.*:
  type: config_entity
  label: Finder
  mapping:
    id:
      type: text
      label: Machine name
    label:
      type: label
      label: Name
    type:
      type: text
      label: Finder type
    channels:
      # @todo Figure this out.
      type: ignore
      label: Finder channels
    entries:
      type: ignore
      label: Finder entries
