# Schema for LocalGov Finders third party settings on bundle entities.
# This is needed because apparently a schema name wildcard can't be used at the
# start of the schema name, so this must be used in a schema definition for
# every bundle entity config which uses finders.
finders.third_party_settings:
  type: mapping
  label: 'Third party settings'
  mapping:
    finder_type:
      type: string
      label: 'Finder type'
    finder_role:
      type: string
      label: 'Finder role'

node.type.*.third_party.finders:
  type: finders.third_party_settings
