<?php

/**
 * @file
 * Contains hook implementations for the Finders facets module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\LegacyHook;
use Drupal\finders\Entity\FinderInterface;
use Drupal\finders_facets\Hook\FacetsHooks;
use Drupal\finders_facets\Hook\FindersHooks;
use Drupal\finders_facets\Hook\FormAlterHooks;
use Drupal\finders_facets\Hook\WidgetAlterHooks;
use Drupal\search_api\IndexInterface;
use Drupal\views\ViewEntityInterface;

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_form_finder_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(FormAlterHooks::class)->formFinderFormAlter($form, $form_state, $form_id);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_field_widget_single_element_finders_channels_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  \Drupal::service(WidgetAlterHooks::class)->fieldWidgetSingleElementFindersChannelsFormAlter($element, $form_state, $context);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_finders_channel_fields_alter(&$channel_field_definitions, $bundle_entity, $finder) {
  \Drupal::service(FindersHooks::class)->findersChannelFieldsAlter($channel_field_definitions, $bundle_entity, $finder);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_finders_entry_fields_alter(&$channel_field_definitions, $bundle_entity, $finder) {
  \Drupal::service(FindersHooks::class)->findersEntryFieldsAlter($channel_field_definitions, $bundle_entity, $finder);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_finders_index_alter(IndexInterface $index, FinderInterface $finder): void {
  \Drupal::service(FindersHooks::class)->findersIndexAlter($index, $finder);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_finders_view_alter(ViewEntityInterface $view, IndexInterface $index, FinderInterface $finder): void {
  \Drupal::service(FindersHooks::class)->findersViewAlter($view, $index, $finder);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_finders_post_configure(FinderInterface $finder) {
  \Drupal::service(FindersHooks::class)->findersPostConfigure($finder);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function finders_facets_facets_search_api_query_type_mapping_alter($backend_plugin_id, array &$query_types) {
  \Drupal::service(FacetsHooks::class)->facetsSearchApiQueryTypeMappingAlter($backend_plugin_id, $query_types);
}
